"""initial tables"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695a46562692'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_google_id'), 'customers', ['google_id'], unique=True)
    op.create_table('payments',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pass_status', 'fail', name='paymentstatusenum'), nullable=False),
    sa.Column('payment_type', sa.Enum('UPI', 'card', name='paymenttypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('restaurants',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_name', sa.String(), nullable=False),
    sa.Column('area', sa.Enum('Mumbai', 'Bangalore', name='areaenum'), nullable=False),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_index(op.f('ix_restaurants_area'), 'restaurants', ['area'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('food_item', sa.Enum('veg_manchurian', 'chicken_manchurian', 'veg_fried_rice', 'chicken_noodles', name='fooditemenum'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.restaurant_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['payments.transaction_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_index(op.f('ix_restaurants_area'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_customers_google_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###